language: node_js

sudo: true

node_js:
    - "8"
#    - "10"

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - DEPLOY="true"
        - MAIN="true"
    - os: linux
      dist: trusty
      env:
        - DEPLOY="false"
        - ARCH="arm"

before_install:
#    - npm i -g npm@latest
    - if [ -z "$ARCH" ]; then sudo apt-get install -y libasound2-dev; fi
    - if [ -n "$ARCH" ]; then sudo sed 's~\(\(deb\(-src\)*\) \([^\[]\)\)~\2 [arch=amd64] \4~' /etc/apt/sources.list | sudo tee /etc/apt/sources.list && sudo bash -c 'echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ trusty main multiverse restricted universe" > /etc/apt/sources.list.d/arm-repo.list' && sudo dpkg --add-architecture armhf && sudo apt-get update && sudo apt-get install -y crossbuild-essential-armhf && sudo apt-get install -y libasound2-dev:armhf; fi

install:
  - if [ -n "$ARCH" ]; then bash ./build-arm.sh; fi
  - if [ -z "$ARCH" ]; then npm install; fi

script:
    - if [ -z "$ARCH" ]; then npm run test:ci; fi
