dist: trusty
language: node_js

sudo: true

node_js:
    - "8"
    - "9"
    - "10"

before_install:
    - npm i -g npm@latest
    - sudo apt-get install -y libasound2-dev

script:
    - npm run test:ci
