language: node_js

sudo: true

node_js:
    - "8"
#    - "10"

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - DEPLOY="true"
        - MAIN="true"
    - os: linux
      dist: trusty
      env:
        - DEPLOY="false"
        - ARCH="arm"

before_install:
#    - npm i -g npm@latest
    - if [ -z "$ARCH" ]; then sudo apt-get install -y libasound2-dev; fi
    - if [ -n "$ARCH" ]; then sudo apt-get install -y software-properties-common && sudo add-apt-repository deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial main multiverse restricted universe && sudo apt-get update && sudo apt-get install -y libasound2-dev:armhf; fi

install:
  - if [ -n "$ARCH" ]; then bash ./build-arm.sh; fi
  - if [ -z "$ARCH" ]; then npm install; fi

script:
    - if [ -z "$ARCH" ]; then npm run test:ci; fi
